- name: configure hosts
  include_role:
    name: bertvv.hosts
  vars:
    hosts_entries:
      - name: "apps.{{ cluster_name }}.{{ domain_name }}"
        ip: "{{ haproxyip }}"
      - name: "{{ cluster_name }}.{{ domain_name }}"
        ip: "{{ haproxyip }}"
- name: configure dnsmasq
  include_role:
    name: bertvv.dnsmasq
  vars:
    dnsmasq_domain: "{{ cluster_name }}.{{ domain_name }}"
    dnsmasq_interface:  eth0
    dnsmasq_dhcp_ranges:
      - start_addr: "{{ start_addr }}"
        end_addr: "{{ end_addr }}"
        lease_time: '10m'
    dnsmasq_srv_hosts:
      - name: "_etcd-server-ssl._tcp.{{ cluster_name }}.{{ domain_name }}"
        target: etcd-0.{{ cluster_name }}.{{ domain_name }}
        port: 2380
        priority: 0
        weight: 10
      - name: "_etcd-server-ssl._tcp.{{ cluster_name }}.{{ domain_name }}"
        target: etcd-1.{{ cluster_name }}.{{ domain_name }}
        port: 2380
        priority: 0
        weight: 10
      - name: "_etcd-server-ssl._tcp.{{ cluster_name }}.{{ domain_name }}"
        target: etcd-2.{{ cluster_name }}.{{ domain_name }}
        port: 2380
        priority: 0
        weight: 10
- name : Addlines for pxeboot to dnsmasq
  lineinfile:
    path: /etc/dnsmasq.conf
    line: pxe-service=x86PC, "install coreos", pxelinux
    state: present
- name : Addlines for pxeboot to dnsmasq
  lineinfile:
    path: /etc/dnsmasq.conf
    line: enable-tftp
    state: present
- name : Addlines for pxeboot to dnsmasq
  lineinfile:
    path: /etc/dnsmasq.conf
    line: tftp-root=/var/lib/tftpboot
    state: present

- name : Addlines for pxeboot to dnsmasq
  lineinfile:
    path: /etc/dnsmasq.conf
    line: read-ethers
    state: present

- name : Addlines for reverse
  lineinfile:
    path: /etc/dnsmasq.conf
    line: "server=/{{ reverseipdnsmasq }}/{{ haproxyip }}"

- name : Addlines for local directive
  lineinfile:
    path: /etc/dnsmasq.conf
    line: "local=/{{ cluster_name }}.{{ domain_name }}/"
 

- name : Addlines for wildcard to dnsmasq
  lineinfile:
    path: /etc/dnsmasq.conf
    line: "address=/apps.{{ cluster_name }}.{{ domain_name }}/{{ haproxyip }}"
    state: present

- name : Addlines for router to dnsmasq
  lineinfile:
    path: /etc/dnsmasq.conf
    line: "dhcp-option=3,{{ routerip }}"
    state: present

- name : Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

